# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    # The publishToSonatype task and the repository release need to be in the same Gradle call
      # so that the closeAndRelease task knows which staging repository was created by publishToSonatype
    - name: Build and publish to OSS Sonatype and then Maven Central
      uses: gradle/gradle-build-action@v2
      env:
        # GPG keys for signing plugin (sign maven artifacts)
        # see https://docs.gradle.org/current/userguide/signing_plugin.html#sec:in-memory-keys
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SECRET_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
        # Credentials implicitly read by the gradle-nexus-publish-plugin
        # https://github.com/gradle-nexus/publish-plugin#publishing-to-maven-central-via-sonatype-ossrh
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USER }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_SECRET }}
      with:
        arguments: |
          publishToSonatype
          closeAndReleaseSonatypeStagingRepository
